#!/bin/bash

ABSPATH=$(cd "$(dirname "$0")"; pwd)

echo ""
echo ""
echo "-=== ALL PARAMS ===-"
echo $@
echo ""
echo ""
# remove -I arguments as they are merely relative paths, hercules needs direct paths
FILTEREDPARAMS=$(echo `$ABSPATH/filterargs $@` | sed "s|-I [^-]*||g")
FNAME=`$ABSPATH/filtername $@ | tr -d ' '`

FNAME=`pwd`/$FNAME

echo "-=== FILTERED PARAMS ===-"
echo $FILTEREDPARAMS
echo filename "$FNAME"

echo ""
echo ""
/usr/bin/gcc $@

# set output files
outBase="$(dirname $FNAME)/$(basename $FNAME .c)"
outDbg="$outBase.dbg"
outPartialPreproc="$outBase.pi"
outErr="$outBase.err"
outTime="$outBase.time"

# base parameters, added direct -I paths l. 41-43
baseParam="
	--bdd --no-warnings \
	-I /usr/local/include \
	-I /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed \
	-I /usr/lib/gcc/x86_64-linux-gnu/4.6/include \
	-I /usr/include/x86_64-linux-gnu \
	-I /usr/include \
    -I $ABSPATH \
	-I $ABSPATH/include \
	-I $ABSPATH/include/openssl
	--platfromHeader    $ABSPATH/platform.h \
	--openFeat          $ABSPATH/openfeatures.txt \
	--featureModelFExpr $ABSPATH/fm.txt \
	--typeSystemFeatureModelDimacs $ABSPATH/OpenSSL.dimacs \
	--include $ABSPATH/partial_configuration.h \
	--serializeAST \
	--interface --debugInterface \
	--recordTiming --parserstatistics --lexNoStdout \
	--writePI $FILTEREDPARAMS "

# run typechef only in case we have a c file
if [[ -n $FNAME ]];
then

	echo "Starting Hercules."
	# TypeChef resides next to TypeChef-<projectname> two levels up
	# create the serialized AST in the first run
	# apply sampling and family-based analysis for each strategy afterwards
	# in a single run
	$ABSPATH/../../Hercules/ifdeftoif.sh \
		$baseParam \
		$FNAME
		2> "$outErr" | tee -a "$outDbg"
fi

echo "Finished"
echo ""
